version: '3'
services:
    web:
        image: mearn-app
        build: .
        command: 'node index.js'
        ports:
            - '8081:8081'
        depends_on:
            - 'mongo'
    mongo:
        image: 'mongo'
        ports:
            - '27017:27017'
